export const FORTUNE_NAME = "projectseed-iowa-production"
export const BDS_NAME = "projectseed-bds-production"
export const SIMON_NAME = "projectseed-simon-production"
export const CS_NAME = "projectseed-cs-production"
export const BDS_TRIALS = 14
export const SIMON_TRIALS = 32
export const CS_TRIALS = 33
export const REPORT_DT_FORMAT = "MM/dd/yyyy HH:mm";
export const REPORT_DT_HM_FORMAT = "HH:mm";